In [1]:
!git clone https://github.com/yurysalyatov/gft-custom.git

Cloning into 'gft-custom'...
remote: Enumerating objects: 565, done.
remote: Counting objects: 100% (218/218), done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 565 (delta 135), reused 132 (delta 62), pack-reused 347 (from 1)
Receiving objects: 100% (565/565), 1.45 GiB | 29.49 MiB/s, done.
Resolving deltas: 100% (205/205), done.
Updating files: 100% (127/127), done.


In [2]:
%cd gft-custom

/kaggle/working/gft-custom


In [3]:
!git pull

Already up to date.


In [4]:
!nvidia-smi

Wed Aug 26 08:16:42 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.04             Driver Version: 580.159.04     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
# Установка PyTorch с CUDA
!pip install torch --index-url https://download.pytorch.org/whl/cu128

# Установка PyTorch Geometric
import torch
print(torch.__version__)
import os
os.environ['TORCH'] = torch.__version__

!pip install torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install pyg-lib -f https://data.pyg.org/whl/nightly/torch-${TORCH}.html
!pip install git+https://github.com/pyg-team/pytorch_geometric.git

# Установка остальных зависимостей из requirements.txt
!pip install -r requirements.txt

# Проверка установки
import torch
print(torch.__version__)
print(torch.cuda.is_available())

Looking in indexes: https://download.pytorch.org/whl/cu128
2.10.0+cu128
Looking in links: https://data.pyg.org/whl/torch-2.10.0+cu128.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 103.1 MB/s eta 0:00:00
Looking in links: https://data.pyg.org/whl/torch-2.10.0+cu128.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 65.6 MB/s eta 0:00:00
Looking in links: https://data.pyg.org/whl/nightly/torch-2.10.0+cu128.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 6.0 MB/s eta 0:00:00
  Cloning https://github.com/pyg-team/pytorch_geometric.git to /tmp/pip-req-build-wpz3x3ad
  Running command git clone --filter=blob:none --quiet https://github.com/pyg-team/pytorch_geometric.git /tmp/pip-req-build-wpz3x3ad
  Resolved https://github.com/pyg-team/pytorch_geometric.git to commit c7ccd0751564153dcffcbff03aea2829fa8db57e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created 

In [6]:
# !pip install lightning

In [7]:
# !pip install rdkit

In [8]:
!ls 

 assets			  environment.yml	     rename_files.py
 change_yaml_config.py	  GFT			     requirements.txt
 ckpts			  GFT_run.ipynb		     script
 config			  LICENSE		     test.py
 data			  notebook55ba2ff0a6.ipynb   utils.py
 embeddings_by_type.npz   process_datasets.py	    'диаграмма процесса.jpg'
 embeddings_by_type.pkl   README.md


In [9]:
!git pull

Already up to date.


In [10]:
# import os

# # Точный путь к данным (проверьте, что внутри есть папка data или сразу файлы)
# source_path = "/kaggle/input/datasets/yurysalyatov/gft-data/data"

# # Если в рабочей директории уже есть папка или ссылка с именем "data" – удаляем
# if os.path.exists("data"):
#     !rm -rf data   # осторожно, но безопасно, т.к. это только ссылка или локальная папка

# # Создаём символическую ссылку (флаг -sf: перезапись, если есть)
# !ln -sf {source_path} data

# # Проверяем, что ссылка работает – должны увидеть содержимое ваших данных
# !ls -la data

In [11]:
import os

# Точный путь к данным (проверьте, что внутри есть папка data или сразу файлы)
source_path = "/kaggle/input/datasets/yurysalyatov/pretrain-gft-model-256codebook/codebook_size_256_layer_2_pretrain_on_aminer_arnetminer_kisti_pbmed_qian_zbmath_seed_42"

path_to_insert = "ckpts/pretrain_model/codebook_size_256_layer_2_pretrain_on_aminer_arnetminer_kisti_pbmed_qian_zbmath_seed_42"

# Если в рабочей директории уже есть папка или ссылка с именем "graph_dir" – удаляем
if os.path.exists(path_to_insert):
    !rm -rf {path_to_insert}   # осторожно, но безопасно, т.к. это только ссылка или локальная папка

# Создаём символическую ссылку (флаг -sf: перезапись, если есть)
!ln -sf {source_path} {path_to_insert}

# Проверяем, что ссылка работает – должны увидеть содержимое ваших данных
!ls -la {path_to_insert}

lrwxrwxrwx 1 root root 154 Aug 26 08:17 ckpts/pretrain_model/codebook_size_256_layer_2_pretrain_on_aminer_arnetminer_kisti_pbmed_qian_zbmath_seed_42 -> /kaggle/input/datasets/yurysalyatov/pretrain-gft-model-256codebook/codebook_size_256_layer_2_pretrain_on_aminer_arnetminer_kisti_pbmed_qian_zbmath_seed_42


In [12]:
import os

# Точный путь к данным (проверьте, что внутри есть папка data или сразу файлы)
source_path = "/kaggle/input/datasets/yurysalyatov/homo-for-gft"

# Если в рабочей директории уже есть папка или ссылка с именем "graph_dir" – удаляем
if os.path.exists("graph_dir/"):
    !rm -rf graph_dir2   # осторожно, но безопасно, т.к. это только ссылка или локальная папка

# Создаём символическую ссылку (флаг -sf: перезапись, если есть)
!ln -sf {source_path} graph_dir

# Проверяем, что ссылка работает – должны увидеть содержимое ваших данных
!ls -la graph_dir

lrwxrwxrwx 1 root root 48 Aug 26 08:17 graph_dir -> /kaggle/input/datasets/yurysalyatov/homo-for-gft


In [13]:
# Предобработка всех шести датасетов
# !python process_datasets.py --datasets aminer,arnetminer,kisti,pbmed,qian,zbmath

In [14]:
!python rename_files.py --datasets aminer,arnetminer,kisti,pbmed,qian,zbmath

/kaggle/working/gft-custom/kaggle/working/gft-custom/graph_dir/
before rename
torch.Size([426635, 768])
torch.Size([426635])
tensor(426634)



tensor([ 0.0289, -0.0390,  0.0084, -0.0908,  0.0064,  0.0326,  0.0297,  0.0310,
         0.0033, -0.0143])
tensor([ 0.0289, -0.0390,  0.0084, -0.0908,  0.0064,  0.0326,  0.0297,  0.0310,
         0.0033, -0.0143])
tensor([ 0.0257,  0.0107,  0.0155,  0.0489, -0.0544,  0.0333,  0.0291,  0.0314,
         0.0271, -0.0340])
tensor([ 0.0257,  0.0107,  0.0155,  0.0489, -0.0544,  0.0333,  0.0291,  0.0314,
         0.0271, -0.0340])
after rename
torch.Size([426635, 768])
torch.Size([426635])
tensor(426634)



before rename
torch.Size([23460, 768])
torch.Size([23460])
tensor(23459)



tensor([-0.0265,  0.0690, -0.0149,  0.0214,  0.0184,  0.0275,  0.0237, -0.0114,
        -0.0419,  0.0176])
tensor([-0.0265,  0.0690, -0.0149,  0.0214,  0.0184,  0.0275,  0.0237, -0.0114,
        -0.0419,  0.0176])
tensor([ 0.0122,  0.0075,  0.0407,  0.0335, -0.0246,  0.0337,

In [15]:
import itertools
import os

all_datasets = ['aminer', 'arnetminer', 'kisti', 'pbmed', 'qian', 'zbmath']
# all_datasets = ['arnetminer', 'pbmed', 'qian', 'zbmath']
# Генерируем все непустые подмножества (2^6 - 1 = 63)
dataset_sets = []
for r in range(1, len(all_datasets) + 1):
    for combo in itertools.combinations(all_datasets, r):
        dataset_sets.append(list(combo))

print(f"Всего наборов: {len(dataset_sets)}")
# Для отладки выведем первые 5
for i, s in enumerate(dataset_sets[:5]):
    print(f"{i+1}: {s}")
# dataset_sets = dataset_sets[:5]
# dataset_sets = dataset_sets[5:10]
# dataset_sets = dataset_sets[10:15]
# dataset_sets = dataset_sets[15:20]
# dataset_sets = dataset_sets[-8:]
dataset_sets = [
    # ['aminer'],
    # ['arnetminer'],
    # ['kisti'],
    # ['pbmed'],
    # ['qian'],
    # ['zbmath'],
    ['aminer', 'arnetminer', 'kisti', 'pbmed', 'qian', 'zbmath'],
    # ['aminer', 'arnetminer', 'kisti', 'pbmed', 'qian'],
    # ['aminer', 'arnetminer', 'kisti', 'pbmed', 'zbmath'],
    # ['aminer', 'arnetminer', 'kisti', 'qian', 'zbmath'],
    # ['aminer', 'arnetminer', 'pbmed', 'qian', 'zbmath'],
    # ['aminer', 'kisti', 'pbmed', 'qian', 'zbmath'],
    # ['arnetminer', 'kisti', 'pbmed', 'qian', 'zbmath'],
]

Всего наборов: 63
1: ['aminer']
2: ['arnetminer']
3: ['kisti']
4: ['pbmed']
5: ['qian']


In [16]:
import yaml
# ===== Загружаем конфиг pretrain.yaml для получения параметров модели =====
with open('config/pretrain.yaml', 'r') as f:
    pretrain_config = yaml.safe_load(f)

# Рекурсивный поиск значения по ключу в словаре (разной вложенности)
def find_param(cfg, key):
    if key in cfg:
        return cfg[key]
    for v in cfg.values():
        if isinstance(v, dict):
            val = find_param(v, key)
            if val is not None:
                return val
    return None

codebook_size = find_param(pretrain_config, 'codebook_size')
num_layers = find_param(pretrain_config, 'num_layers')
if num_layers is None:
    num_layers = find_param(pretrain_config, 'layers')

if None in (codebook_size, num_layers):
    raise ValueError("Не удалось найти все необходимые параметры (codebook_size, num_layers/layers, seed) в config/pretrain.yaml")
print(f"codebook size:{codebook_size}\nlayers:{num_layers}")

codebook size:256
layers:2


In [17]:
import os
import shutil
import time
import glob
import re

base_ckpt = 'ckpts/pretrain_model'
embeddings_root = 'embeddings'
epoch_to_load = 50  # эпоха, которую будем использовать для извлечения (можно менять)

# Создаём корневые папки
os.makedirs(base_ckpt, exist_ok=True)
os.makedirs(embeddings_root, exist_ok=True)

for idx, dataset_list in enumerate(dataset_sets):
    set_name = '_'.join(dataset_list)  # например "arnetminer_qian"
    print(f"\n=== Обработка набора {idx+1}/{len(dataset_sets)}: {set_name} ===")
    start_time = time.time()

    # 1. Обновляем конфиг для обучения
    # !python change_yaml_config.py --datasets {','.join(dataset_list)} --config config/pt_data.yaml --default_weight 5.0

    # 2. Запускаем предобучение с сохранением в отдельную папку
    save_dir = f"{base_ckpt}/"
    !mkdir -p {save_dir}
    # !python GFT/pretrain.py --use_params --debug --save_dir {save_dir} --save_name {set_name}
    
    checkpoint_folder = f"{base_ckpt}/codebook_size_{codebook_size}_layer_{num_layers}_pretrain_on_{set_name}_seed_42"

    encoder_files = glob.glob(os.path.join(checkpoint_folder, "encoder_*.pt"))
    epochs = []
    for f in encoder_files:
        match = re.search(r'encoder_(\d+)\.pt', os.path.basename(f))
        if match:
            epochs.append(int(match.group(1)))
    if not epochs:
        raise FileNotFoundError(f"Не найдено файлов encoder_*.pt в {checkpoint_folder}")
    max_epoch = max(epochs)
    print(f"Используется максимальная эпоха: {max_epoch}")

    epoch_to_load = max_epoch
    
    dst_model = f"{embeddings_root}/{set_name}/codebook_size_{codebook_size}_layer_{num_layers}_pretrain_on_{set_name}_seed_42"
    encoder = f"{checkpoint_folder}/encoder_{epoch_to_load}.pt"
    vq = f"{checkpoint_folder}/vq_{epoch_to_load}.pt"
    os.makedirs(dst_model, exist_ok=True)
    # shutil.move(encoder, f"{dst_model}/encoder_{epoch_to_load}.pt")
    # shutil.move(vq, f"{dst_model}/vq_{epoch_to_load}.pt")
    info_file = f"{checkpoint_folder}/info.txt"
    # if os.path.exists(info_file):
        # shutil.move(info_file, f"{dst_model}/info.txt")
    # shutil.rmtree(checkpoint_folder)
    # 3. Извлекаем эмбеддинги для ВСЕХ датасетов (из all_datasets)
    for ds in all_datasets:
        print(f"  Извлечение для {ds}...")
        out_dir = f"{embeddings_root}/{set_name}/{ds}"
        !python GFT/extract_embs.py --dataset {ds} --checkpoint_dir {checkpoint_folder} --epoch {epoch_to_load} --output_dir {out_dir}

    elapsed = time.time() - start_time
    print(f"Набор {set_name} завершён за {elapsed:.2f} сек.")

print("Все наборы обработаны.")


=== Обработка набора 1/1: aminer_arnetminer_kisti_pbmed_qian_zbmath ===
Используется максимальная эпоха: 100
  Извлечение для aminer...
/kaggle/working/gft-custom/GFT/model/vq.py:438: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
/kaggle/working/gft-custom/GFT/model/vq.py:623: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
Loading model from ckpts/pretrain_model/codebook_size_256_layer_2_pretrain_on_aminer_arnetminer_kisti_pbmed_qian_zbmath_seed_42, epoch 100
Model parameters: {'input_dim': 768, 'hidden_dim': 768, 'num_layers': 2, 'activation': 'relu', 'backbone': 'sage', 'normalize': 'batch', 'dropout': 0.15, 'codebook_size': 256, 'code_dim': 768, 'codebook_head': 4}
Loading graph aminer...
Extracting embeddings in batches...
Extracting embeddings: 100%|██████████████████| 334

In [18]:
# Упаковываем папку с эмбеддингами в zip-архив
!zip -r /kaggle/working/embeddings_all.zip embeddings/
print("Архив embeddings_all.zip создан. Скачайте его через интерфейс Kaggle.")

  adding: embeddings/ (stored 0%)
  adding: embeddings/aminer_arnetminer_kisti_pbmed_qian_zbmath/ (stored 0%)
  adding: embeddings/aminer_arnetminer_kisti_pbmed_qian_zbmath/aminer/ (stored 0%)
  adding: embeddings/aminer_arnetminer_kisti_pbmed_qian_zbmath/aminer/aminer_embeddings.pkl (deflated 91%)
  adding: embeddings/aminer_arnetminer_kisti_pbmed_qian_zbmath/qian/ (stored 0%)
  adding: embeddings/aminer_arnetminer_kisti_pbmed_qian_zbmath/qian/qian_embeddings.pkl (deflated 93%)
  adding: embeddings/aminer_arnetminer_kisti_pbmed_qian_zbmath/zbmath/ (stored 0%)
  adding: embeddings/aminer_arnetminer_kisti_pbmed_qian_zbmath/zbmath/zbmath_embeddings.pkl (deflated 93%)
  adding: embeddings/aminer_arnetminer_kisti_pbmed_qian_zbmath/codebook_size_256_layer_2_pretrain_on_aminer_arnetminer_kisti_pbmed_qian_zbmath_seed_42/ (stored 0%)
  adding: embeddings/aminer_arnetminer_kisti_pbmed_qian_zbmath/arnetminer/ (stored 0%)
  adding: embeddings/aminer_arnetminer_kisti_pbmed_qian_zbmath/arnetminer/a